# Generated by Django 5.0.6 on 2024-05-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarqatuvchi',
            options={'verbose_name': 'Tarqatuvchi', 'verbose_name_plural': 'Tarqatuvchilar'},
        ),
    ]
